set nocompatible " Must be the first line
" DO NOT EDIT THE NEXT LINE, this is autogenerated

 
" Everything here is just, like, Dave's opinion or whatever.  Probably should
" edit this to be what you really want.
" === Global Settings ===
set modeline
set encoding=utf-8
set mouse=a
set ignorecase
set smartcase
set foldenable
set foldmethod=marker
set t_Co=256
set backspace=indent,eol,start 
set incsearch
set lazyredraw
set showmatch
set showcmd
set hlsearch
set nu
set ruler
set autoread
set nobackup
set noerrorbells
set novisualbell
set t_vb=
set background=dark
set colorcolumn=80
colorscheme solarized
set tm=500
" let $MYVIMRC="$SUITCASE/vim/vimrc"

" === Syntax Highlighting & auto-indent ===
let python_highlight_all=1
syntax on
syntax enable
set ofu=syntaxcomplete#Complete
set antialias
filetype on
filetype plugin on 
filetype indent on
set autoindent
set smartindent
set number

" === Wildmenu ===
set wildmenu
set wildmode=longest,list,full
set wildignore=.svn,CVS,*.o,*.a,*.class,*.mo,*.la,*.so,*.obj,*.swp,*.jpg,*.png,*.xpm,*.gif

" === Coding tweaks ===
fu Carlos_style()
  set shiftwidth=2
  set expandtab
  set tabstop=2
  set softtabstop=2
  set shiftwidth=2
endf
au BufRead,BufNewFile *py,*pyw,*.c,*.h,*.cpp call Carlos_style()
au BufRead,BufNewFile Makefile* set noexpandtab

" K settings
au BufRead,BufNewFile *.k set filetype=k3
au BufRead,BufNewFile *.k call Carlos_style()

" strace settings
au BufRead,BufNewFile *.strace set filetype=strace

" Use the below highlight group when displaying bad whitespace is desired.
highlight BadWhitespace ctermbg=red guibg=red
" Display tabs at the beginning of a line in Python mode as bad.
au BufRead,BufNewFile *.py,*.pyw match BadWhitespace /^\t\+/
au BufRead,BufNewFile *.k,*.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/
 
" Python: not needed, C: prevents insertion of '*' at the beginning of every line in a comment
au BufRead,BufNewFile *.c,*.h set formatoptions-=c formatoptions-=o formatoptions-=r
 
" " Custom Status Line
set statusline=   " clear the statusline for when vimrc is reloaded
set statusline+=%-3.3n\                      " buffer number
set statusline+=%f\                          " file name
set statusline+=%h%m%r%w                     " flags
set statusline+=[%{strlen(&ft)?&ft:'none'},  " filetype
set statusline+=%{strlen(&fenc)?&fenc:&enc}, " encoding
set statusline+=%{&fileformat}]              " file format
set statusline+=%=                           " right align
set statusline+=%{synIDattr(synID(line('.'),col('.'),1),'name')}\  " highlight
set statusline+=%b,0x%-8B\                   " current char
set statusline+=%-14.(%l,%c%V%)\ %<%P        " offset
set laststatus=2
